import = ["/home/shayan/.config/alacritty/tokyo-night.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "CaskaydiaMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaMono Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[shell]
program = "/usr/bin/tmux"
args = ["-f", "/home/shayan/.config/tmux/tmux.conf"]

[window]
opacity = 1
decorations = "None"
dynamic_padding = true

[window.dimensions]
columns = 0
lines = 0

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 2
y = 0

[mouse]
hide_when_typing = true
